version: "2"
services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    build: ${PROJECT_ROOT}/foodbasket-api/
    ports:
      - 6000:9000
    volumes:
      - ${PROJECT_ROOT}/foodbasket-api/:/app
      - /app/vendor
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://foodbasket@postgres/foodbasket
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: foodbasket
      POSTGRES_DB: foodbasket
      POSTGRES_PASSWORD: 1111
    ports:
      - 3306:5432
    volumes:
      - ../PostgresData/data:/var/lib/postgresql/data
  redis:
    build: ./Redis/
    ports:
      - 6309:6379
    volumes:
      - ../RedisData/data:/data
    command: redis-server --appendonly yes
    depends_on:
      - api
